--DROP DATABASE ***REMOVED***;
--DROP DATABASE ***REMOVED***2;
CREATE DATABASE IF NOT EXISTS ***REMOVED*** CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS ***REMOVED***2 CHARACTER SET utf8 COLLATE utf8_general_ci;
